services:
  easyscan-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - valkey
    environment:
      REDIS_URL: redis://valkey:6379

  valkey:
    image: valkey/valkey:bookworm
    volumes:
      - valkey-data:/data

volumes:
  valkey-data: